version: '3'
name: free-jam
services:
  caddy:
    image: caddy:alpine
    ports:
      - 80:80
    volumes:
      - ./tools/caddy:/etc/caddy
  # debug:
  #   image: busybox
  #   command: ['sleep', '9999']
  db:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=sSXf2q8gA6jQZ5
      - MSSQL_PID=Evaluation
  bucket:
    image: quay.io/minio/minio
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
    ports:
      - 9090:9090
    command: server /data --console-address ":9090"
  # backend:
  #     build:
  #       context: ./backend
  #       dockerfile: Dockerfile
  #     volumes:
  #       - ./backend:/app
  #     environment:
  #       - ASPNETCORE_ENVIRONMENT=Development
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
  data-seed:
    build:
      context: ./tools/seed-data
      dockerfile: Dockerfile
    volumes:
      - ./tools/seed-data:/app

# TODO:
# - data-seed should wait until API is online
# - data-seed should not do anything if there is already data in the API
# - migration auto applied by backend
# - auto bucket creation by backend

# TODO vandaag;
# - figma
# - doc tool
# - misschien wat onderzoek naar hoe chord detecteren?