version: '3'
name: free-jam
services:
  caddy:
    image: caddy:alpine
    ports:
      - 3010:80
    volumes:
      - ./tools/caddy:/etc/caddy
  # debug:
  #   image: busybox
  #   command: ['sleep', '9999']
  db:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=sSXf2q8gA6jQZ5
      - MSSQL_PID=Evaluation
  bucket:
    image: quay.io/minio/minio
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
    ports:
      - 9090:9090
      - 9000:9000
    command: server /data --console-address ":9090"
  backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      # ports:
      #   - 5074:5074
      volumes:
        - ./backend:/app
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # ports:
    #   - 3000:3000
    volumes:
      - ./frontend:/app
  # data-seed:
  #   volumes:
  #     - ./tools/seed-data:/app
  #   # work-dir: /app
  #   command: ['npm', 'install', '&&', 'seed.js']